package cl.will.codepadai;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.text.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity {
 private static final int PICK_FILE=41,PICK_ZIP=42; private LinearLayout root,side,tabs,aiPanel; private CodeEditText editor; private LineNumberView lineNumbers; private TextView status,aiSizeButton; private EditText aiInput; private ScrollView aiScroll; private ListView browser; private File workspace,currentDir,projectRoot; private String projectContext=""; private final ArrayList<DocumentTab> docs=new ArrayList<DocumentTab>(); private final HashSet<String> contextAttempts=new HashSet<String>(); private DocumentTab active; private boolean binding,sideVisible=true,wrapLines=false; private int aiPanelSize=0; private Handler handler=new Handler(); private Runnable highlightTask;
 private ChatTranscript aiHistory; private String savedConversation="",conversationContexts="",lastContextRecord=""; private boolean chatClosePrompt;
 private TextView readButton,devButton,aiScope; private boolean readOnly=false,devMode=false; private AIClient.Request aiRequest; private int aiSequence=0;
 private int brown=Color.rgb(100,65,45), cream=Color.rgb(250,248,244); private final ArrayDeque<String> undo=new ArrayDeque<String>(), redo=new ArrayDeque<String>();

 public void onCreate(Bundle b){super.onCreate(b); workspace=new File(getExternalFilesDir(null),"workspaces");workspace.mkdirs();wrapLines=getSharedPreferences("editor",0).getBoolean("wrap",false);buildUi();if(b!=null)restoreSession(b);else showHome();}
 private TextView button(String text){TextView v=new TextView(this);v.setText(text);v.setTextColor(Color.WHITE);v.setGravity(Gravity.CENTER);v.setPadding(12,8,12,8);v.setBackgroundColor(brown);return v;}
 private void buildUi(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(cream);
  LinearLayout top=new LinearLayout(this); top.setGravity(Gravity.CENTER_VERTICAL); TextView menu=button("☰");top.addView(menu,new LinearLayout.LayoutParams(52,44)); HorizontalScrollView tabScroll=new HorizontalScrollView(this);tabs=new LinearLayout(this);tabScroll.addView(tabs);top.addView(tabScroll,new LinearLayout.LayoutParams(0,44,1));readButton=button("✎ EDITANDO");top.addView(readButton,new LinearLayout.LayoutParams(dp(88),44));TextView more=button("⋮");top.addView(more,new LinearLayout.LayoutParams(48,44));root.addView(top);
  LinearLayout body=new LinearLayout(this);side=new LinearLayout(this);side.setOrientation(LinearLayout.VERTICAL);side.setBackgroundColor(Color.rgb(235,229,222));
  LinearLayout modes=new LinearLayout(this);TextView project=button("PROYECTO"), symbols=button("SÍMBOLOS");modes.addView(project,new LinearLayout.LayoutParams(0,38,1));modes.addView(symbols,new LinearLayout.LayoutParams(0,38,1));side.addView(modes);browser=new ListView(this);side.addView(browser,new LinearLayout.LayoutParams(-1,0,1));body.addView(side,new LinearLayout.LayoutParams(dp(185),-1));
  LinearLayout codeArea=new LinearLayout(this);lineNumbers=new LineNumberView(this);editor=new CodeEditText(this);lineNumbers.attach(editor);codeArea.addView(lineNumbers,new LinearLayout.LayoutParams(dp(46),-1));editor.setGravity(Gravity.TOP|Gravity.LEFT);editor.setTextSize(14);editor.setTextColor(Color.rgb(40,40,40));editor.setBackgroundColor(Color.WHITE);editor.setTypeface(Typeface.MONOSPACE);editor.setPadding(10,8,10,8);editor.setSingleLine(false);editor.setHorizontallyScrolling(!wrapLines);editor.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE|android.text.InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);codeArea.addView(editor,new LinearLayout.LayoutParams(0,-1,1));body.addView(codeArea,new LinearLayout.LayoutParams(0,-1,1));root.addView(body,new LinearLayout.LayoutParams(-1,0,1));
  buildAiPanel();editor.backAction=new Runnable(){public void run(){requestCloseChat();}};editor.chatVisible=new CodeEditText.ChatVisible(){public boolean isVisible(){return aiPanel.getVisibility()==View.VISIBLE;}};root.addView(aiPanel,new LinearLayout.LayoutParams(-1,dp(150)));aiPanel.setVisibility(View.GONE);
  LinearLayout bottom=new LinearLayout(this);status=new TextView(this);status.setText("Sin archivo");status.setPadding(10,6,4,6);bottom.addView(status,new LinearLayout.LayoutParams(0,36,1));TextView ai=button("IA");bottom.addView(ai,new LinearLayout.LayoutParams(76,36));root.addView(bottom);
  FrameLayout stage=new FrameLayout(this);stage.addView(root,new FrameLayout.LayoutParams(-1,-1));stage.addView(makeSymbolPalette());setContentView(stage);
  menu.setOnClickListener(new View.OnClickListener(){public void onClick(View v){sideVisible=!sideVisible;side.setVisibility(sideVisible?View.VISIBLE:View.GONE);}});readButton.setOnClickListener(new View.OnClickListener(){public void onClick(View v){setReadOnly(!readOnly);}});more.setOnClickListener(new View.OnClickListener(){public void onClick(View v){showMenu(v);}});project.setOnClickListener(new View.OnClickListener(){public void onClick(View v){showFiles(currentDir==null?workspace:currentDir);}});symbols.setOnClickListener(new View.OnClickListener(){public void onClick(View v){showSymbols();}});ai.setOnClickListener(new View.OnClickListener(){public void onClick(View v){if(active==null&&aiHistory.getText().toString().indexOf("Tú (")<0){toast("Abre un archivo primero");return;}updateAiScope();if(aiPanel.getVisibility()==View.VISIBLE)requestCloseChat();else aiPanel.setVisibility(View.VISIBLE);}});
  editor.getViewTreeObserver().addOnScrollChangedListener(new ViewTreeObserver.OnScrollChangedListener(){public void onScrollChanged(){lineNumbers.invalidate();}});editor.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){if(!binding&&active!=null){undo.addLast(s.toString());while(undo.size()>40)undo.removeFirst();redo.clear();}}public void onTextChanged(CharSequence s,int st,int b,int c){lineNumbers.invalidate();if(binding||active==null)return;active.text=s.toString();active.dirty=true;active.cursor=editor.getSelectionStart();refreshTabs();scheduleHighlight();updateStatus();}public void afterTextChanged(Editable e){}});
 }
 private void buildAiPanel(){aiPanel=new LinearLayout(this);aiPanel.setOrientation(LinearLayout.VERTICAL);aiPanel.setPadding(dp(6),dp(4),dp(6),dp(4));aiPanel.setBackgroundColor(Color.rgb(239,233,226));
  LinearLayout title=new LinearLayout(this);TextView label=new TextView(this);label.setText("Oliver IA");label.setTextColor(brown);label.setTextSize(16);title.addView(label,new LinearLayout.LayoutParams(-2,dp(32)));TextView faq=button("?");faq.setContentDescription("Preguntas frecuentes");title.addView(faq,new LinearLayout.LayoutParams(dp(40),dp(32)));faq.setOnClickListener(new View.OnClickListener(){public void onClick(View v){showQuestions(v);}});View space=new View(this);title.addView(space,new LinearLayout.LayoutParams(0,1,1));aiScope=new TextView(this);aiScope.setGravity(Gravity.CENTER);aiScope.setTextSize(11);aiScope.setTextColor(Color.DKGRAY);title.addView(aiScope,new LinearLayout.LayoutParams(dp(88),dp(28)));devButton=button("NORMAL");title.addView(devButton,new LinearLayout.LayoutParams(dp(72),dp(28)));aiSizeButton=button("MED");title.addView(aiSizeButton,new LinearLayout.LayoutParams(dp(52),dp(28)));TextView close=button("×");title.addView(close,new LinearLayout.LayoutParams(dp(40),dp(28)));for(int i=0;i<title.getChildCount();i++){View v=title.getChildAt(i);if(v instanceof TextView){v.setPadding(dp(3),dp(2),dp(3),dp(2));((TextView)v).setTextSize(12);}}aiPanel.addView(title);
  aiHistory=new ChatTranscript(this);aiHistory.setText("Pregunta sobre una selección o sobre el archivo completo.\n");aiScroll=new ScrollView(this);aiScroll.addView(aiHistory);aiPanel.addView(aiScroll,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout sendRow=new LinearLayout(this);aiInput=new EditText(this){@Override public boolean onKeyPreIme(int key,KeyEvent e){if(key==KeyEvent.KEYCODE_BACK&&aiPanel.getVisibility()==View.VISIBLE){if(e.getAction()==KeyEvent.ACTION_UP&&!e.isCanceled())requestCloseChat();return true;}return super.onKeyPreIme(key,e);}};aiInput.setHint("Pregunta sobre este código…");aiInput.setSingleLine();sendRow.addView(aiInput,new LinearLayout.LayoutParams(0,dp(42),1));TextView send=button("ENVIAR");sendRow.addView(send,new LinearLayout.LayoutParams(dp(82),dp(42)));aiPanel.addView(sendRow);
  devButton.setOnClickListener(new View.OnClickListener(){public void onClick(View v){devMode=!devMode;devButton.setText(devMode?"DEV":"NORMAL");toast(devMode?"Modo Dev: respuestas extensas":"Modo normal: ahorro de tokens");}});aiSizeButton.setOnClickListener(new View.OnClickListener(){public void onClick(View v){cycleAiPanelSize();}});close.setOnClickListener(new View.OnClickListener(){public void onClick(View v){requestCloseChat();}});send.setOnClickListener(new View.OnClickListener(){public void onClick(View v){askAI();}});
 }
 private void updateAiScope(){if(aiScope==null||editor==null)return;int a=editor.getSelectionStart(),b=editor.getSelectionEnd();aiScope.setText(a!=b?"SELECCIÓN":"ARCHIVO");}
 private void setReadOnly(boolean value){readOnly=value;editor.setReadOnly(value);readButton.setText(value?"👁 LEYENDO":"✎ EDITANDO");toast(value?"Solo lectura: el teclado no se abrirá":"Edición activada");}
 private void cycleAiPanelSize(){aiPanelSize=(aiPanelSize+1)%3;int[] heights={150,260,400};String[] next={"MED","GRANDE","PEQ"};android.view.ViewGroup.LayoutParams lp=aiPanel.getLayoutParams();lp.height=dp(heights[aiPanelSize]);aiPanel.setLayoutParams(lp);aiSizeButton.setText(next[aiPanelSize]);}
 private View makeSymbolPalette(){final LinearLayout bar=new LinearLayout(this);bar.setPadding(2,2,2,2);bar.setBackgroundColor(Color.rgb(72,52,43));final TextView handle=button("↕");bar.addView(handle,new LinearLayout.LayoutParams(dp(36),dp(38)));String[] keys={"\"","'",";",":","(",")","[","]","{","}","<",">","=","+","-","_","/","\\","|","&","!","?","."};for(final String k:keys){TextView b=button(k);b.setBackgroundColor(Color.rgb(110,78,60));b.setOnClickListener(new View.OnClickListener(){public void onClick(View v){insertSymbol(k);}});bar.addView(b,new LinearLayout.LayoutParams(dp(34),dp(38)));}HorizontalScrollView scroll=new HorizontalScrollView(this);scroll.setBackgroundColor(Color.rgb(72,52,43));scroll.addView(bar);final FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(dp(300),dp(42),Gravity.RIGHT|Gravity.TOP);lp.topMargin=dp(58);lp.rightMargin=dp(8);scroll.setLayoutParams(lp);handle.setOnTouchListener(new View.OnTouchListener(){float dx,dy;public boolean onTouch(View v,MotionEvent e){View parent=(View)v.getParent().getParent();if(e.getAction()==MotionEvent.ACTION_DOWN){dx=e.getRawX()-parent.getX();dy=e.getRawY()-parent.getY();return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){parent.setX(Math.max(0,e.getRawX()-dx));parent.setY(Math.max(0,e.getRawY()-dy));return true;}return true;}});return scroll;}
 private void insertSymbol(String s){if(readOnly){toast("Activa edición para insertar símbolos");return;}if(active==null)return;int a=Math.max(0,editor.getSelectionStart()),b=Math.max(0,editor.getSelectionEnd());editor.getText().replace(Math.min(a,b),Math.max(a,b),s);editor.setSelection(Math.min(a,b)+s.length());editor.requestFocus();}
 private void showMenu(View anchor){PopupMenu p=new PopupMenu(this,anchor);p.getMenu().add("Abrir archivo");p.getMenu().add("Abrir proyecto ZIP");p.getMenu().add("Archivo nuevo");p.getMenu().add("Guardar");p.getMenu().add("Guardar todos");p.getMenu().add("Abrir en compilador");p.getMenu().add("Compartir archivo / Bluetooth");p.getMenu().add("Compartir proyecto ZIP");p.getMenu().add("Exportar proyecto ZIP");p.getMenu().add("Buscar");p.getMenu().add("Deshacer");p.getMenu().add("Rehacer");p.getMenu().add(wrapLines?"Desactivar ajuste de línea":"Activar ajuste de línea");p.getMenu().add("Ajustes");p.setOnMenuItemClickListener(new PopupMenu.OnMenuItemClickListener(){public boolean onMenuItemClick(android.view.MenuItem i){String s=i.getTitle().toString();if(s.equals("Abrir archivo"))chooseFile(false);else if(s.equals("Abrir proyecto ZIP"))chooseFile(true);else if(s.equals("Archivo nuevo"))newFile();else if(s.equals("Guardar")){if(save(active))offerConversationSave(null);}else if(s.equals("Guardar todos")){boolean ok=true;for(DocumentTab d:docs)if(!save(d))ok=false;if(ok)offerConversationSave(null);}else if(s.equals("Abrir en compilador"))shareActive(true);else if(s.equals("Compartir archivo / Bluetooth"))shareActive(false);else if(s.equals("Compartir proyecto ZIP"))shareProjectZip();else if(s.equals("Exportar proyecto ZIP"))exportZip();else if(s.equals("Buscar"))findText();else if(s.equals("Deshacer"))undo();else if(s.equals("Rehacer"))redo();else if(s.indexOf("ajuste de línea")>=0)toggleWrap();else startActivity(new Intent(MainActivity.this,SettingsActivity.class));return true;}});p.show();}
 private void toggleWrap(){wrapLines=!wrapLines;editor.setHorizontallyScrolling(!wrapLines);editor.requestLayout();getSharedPreferences("editor",0).edit().putBoolean("wrap",wrapLines).apply();lineNumbers.invalidate();toast(wrapLines?"Ajuste de línea activado":"Ajuste de línea desactivado");}
 private void showHome(){currentDir=workspace;showFiles(workspace);}
 private void showFiles(final File dir){currentDir=dir;final ArrayList<File> fs=new ArrayList<File>();if(dir.getParentFile()!=null&&dir.getAbsolutePath().startsWith(workspace.getAbsolutePath()))fs.add(dir.getParentFile());File[] a=dir.listFiles();if(a!=null){Arrays.sort(a,new Comparator<File>(){public int compare(File x,File y){if(x.isDirectory()!=y.isDirectory())return x.isDirectory()?-1:1;return x.getName().compareToIgnoreCase(y.getName());}});for(File f:a)fs.add(f);}ArrayList<String> names=new ArrayList<String>();for(File f:fs)names.add(f.equals(dir.getParentFile())?"↰ ..":(f.isDirectory()?"▸ ":"  ")+f.getName());browser.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,names));browser.setOnItemClickListener(new android.widget.AdapterView.OnItemClickListener(){public void onItemClick(android.widget.AdapterView<?> a,View v,int pos,long id){File f=fs.get(pos);if(f.isDirectory()){if(f.getParentFile()!=null&&f.getParentFile().equals(workspace)){projectRoot=f;loadProjectContext(f);}showFiles(f);}else openFile(f);}});browser.setOnItemLongClickListener(new android.widget.AdapterView.OnItemLongClickListener(){public boolean onItemLongClick(android.widget.AdapterView<?> a,View v,int pos,long id){final File f=fs.get(pos);if(f.equals(dir.getParentFile()))return true;new AlertDialog.Builder(MainActivity.this).setTitle("Eliminar").setMessage("¿Desea eliminar "+f.getName()+"?").setPositiveButton("ELIMINAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){closeDeletedTabs(f);if(FileUtils.deleteRecursive(f)){showFiles(dir);toast("Eliminado");}else toast("No se pudo eliminar");}}).setNegativeButton("CANCELAR",null).show();return true;}});}
 private void closeDeletedTabs(File f){ArrayList<DocumentTab> copy=new ArrayList<DocumentTab>(docs);for(DocumentTab d:copy)if(d.file.getAbsolutePath().startsWith(f.getAbsolutePath())){docs.remove(d);if(active==d)active=null;}if(active==null){if(!docs.isEmpty())bind(docs.get(0));else{binding=true;editor.setText("");binding=false;refreshTabs();updateStatus();}}}
 private void showSymbols(){final java.util.List<SymbolScanner.Symbol> ss=active==null?new ArrayList<SymbolScanner.Symbol>():SymbolScanner.scan(editor.getText().toString());browser.setAdapter(new ArrayAdapter<SymbolScanner.Symbol>(this,android.R.layout.simple_list_item_1,ss));browser.setOnItemClickListener(new android.widget.AdapterView.OnItemClickListener(){public void onItemClick(android.widget.AdapterView<?> a,View v,int p,long id){int o=ss.get(p).offset;editor.setSelection(Math.min(o,editor.length()));editor.requestFocus();}});}
 private void chooseFile(final boolean zip){try{Intent i=new Intent(Intent.ACTION_GET_CONTENT);i.setType(zip?"application/zip":"*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(Intent.createChooser(i,zip?"Seleccionar proyecto ZIP":"Seleccionar archivo"),zip?PICK_ZIP:PICK_FILE);}catch(Exception e){toast("Instala o activa un administrador de archivos");}}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;try{Uri uri=data.getData();String name=fileName(uri,request==PICK_ZIP?"proyecto.zip":"archivo.txt");File picked=new File(getCacheDir(),name);InputStream in=getContentResolver().openInputStream(uri);FileOutputStream out=new FileOutputStream(picked);byte[] buf=new byte[8192];int n;while((n=in.read(buf))>0)out.write(buf,0,n);in.close();out.close();if(request==PICK_ZIP)importZip(picked);else{File dir=currentDir!=null&&currentDir.isDirectory()?currentDir:workspace;File copy=new File(dir,name);FileUtils.write(copy,FileUtils.read(picked));openFile(copy);showFiles(dir);}}catch(Exception e){error(e);}}
 private String fileName(Uri uri,String fallback){String n=null;android.database.Cursor c=null;try{c=getContentResolver().query(uri,new String[]{android.provider.OpenableColumns.DISPLAY_NAME},null,null,null);if(c!=null&&c.moveToFirst())n=c.getString(0);}catch(Exception ignored){}finally{if(c!=null)c.close();}if(n==null||n.length()==0)n=uri.getLastPathSegment();if(n==null||n.length()==0)n=fallback;int p=n.lastIndexOf('/');if(p>=0)n=n.substring(p+1);return n.replaceAll("[^A-Za-z0-9._() -]","_");}
 private void importZip(final File zip){try{String n=zip.getName().replaceAll("(?i)\\.zip$","")+"_"+System.currentTimeMillis();File out=new File(workspace,n);out.mkdirs();FileUtils.unzip(zip,out);projectRoot=out;loadProjectContext(out);showFiles(out);toast(projectContext.length()>0?"Proyecto importado · README cargado":"Proyecto importado · sin README");}catch(Exception e){error(e);}}
 private void loadProjectContext(File root){cancelAi("Consulta cancelada al cambiar de proyecto.");String key=root.getAbsolutePath();projectContext=getSharedPreferences("contexts",0).getString(key,"");if(projectContext.length()>0){if(aiHistory!=null)aiHistory.append("\nContexto resumido cargado ✓\n");return;}File readme=findReadme(root,0);if(readme!=null)try{String text=FileUtils.read(readme);projectContext=text.substring(0,Math.min(text.length(),12000));if(!contextAttempts.contains(key)){contextAttempts.add(key);if(aiHistory!=null)aiHistory.append("\nREADME encontrado · preparando contexto una vez…\n");summarizeProjectContext(root,readme,text);}}catch(Exception ignored){}}
 private void summarizeProjectContext(final File root,final File readme,String text){android.content.SharedPreferences sp=getSharedPreferences(SettingsActivity.PREF,0);String url=sp.getString(SettingsActivity.URL,"");if(url.length()==0)return;String header=sp.getString(SettingsActivity.HEADER,"X-RetroAI-Key"),secret=sp.getString(SettingsActivity.SECRET,""),model=sp.getString(SettingsActivity.MODEL,"openrouter/free");String limited=text.substring(0,Math.min(text.length(),20000));AIClient.ask(url,header,secret,model,"Resume este README en máximo 1800 caracteres. Conserva propósito, tecnologías, estructura, compilación y decisiones importantes.","markdown",readme.getName(),limited,"",false,new AIClient.Callback(){public void done(final String ans,final Exception e){runOnUiThread(new Runnable(){public void run(){if(e==null&&ans!=null&&ans.length()>0&&projectRoot!=null&&projectRoot.equals(root)){projectContext=ans;getSharedPreferences("contexts",0).edit().putString(root.getAbsolutePath(),ans).apply();if(aiHistory!=null)aiHistory.append("Contexto del proyecto resumido y guardado ✓\n");toast("Contexto README listo");}}});}});}
 private File findReadme(File dir,int depth){if(dir==null||depth>3)return null;String[] preferred={"README.md","README.txt","README"};for(String n:preferred){File f=new File(dir,n);if(f.isFile())return f;}File[] kids=dir.listFiles();if(kids!=null)for(File f:kids)if(f.isDirectory()){File found=findReadme(f,depth+1);if(found!=null)return found;}return null;}
 private void openFile(File f){if(!f.isFile()){toast("No existe el archivo");return;}for(DocumentTab d:docs)if(d.file.equals(f)){bind(d);return;}try{if(f.length()>2*1024*1024){toast("Archivo demasiado grande para esta versión");return;}DocumentTab d=new DocumentTab(f,FileUtils.read(f));docs.add(d);bind(d);}catch(Exception e){error(e);}}
 private void newFile(){final EditText name=new EditText(this);name.setHint("NuevoArchivo.java");new AlertDialog.Builder(this).setTitle("Nuevo archivo").setView(name).setPositiveButton("CREAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){try{File dir=currentDir!=null&&currentDir.isDirectory()?currentDir:workspace;File f=new File(dir,name.getText().toString().trim());FileUtils.write(f,"");openFile(f);showFiles(dir);}catch(Exception e){error(e);}}}).setNegativeButton("CANCELAR",null).show();}
 private void bind(DocumentTab d){if(active!=null)active.cursor=editor.getSelectionStart();active=d;undo.clear();redo.clear();binding=true;editor.setText(d.text);editor.setSelection(Math.min(d.cursor,editor.length()));binding=false;SyntaxHighlighter.apply(editor.getText(),d.file);refreshTabs();updateStatus();}
 private void undo(){if(readOnly||undo.isEmpty())return;redo.addLast(editor.getText().toString());setHistoryText(undo.removeLast());}
 private void redo(){if(readOnly||redo.isEmpty())return;undo.addLast(editor.getText().toString());setHistoryText(redo.removeLast());}
 private void setHistoryText(String s){binding=true;editor.setText(s);binding=false;if(active!=null){active.text=s;active.dirty=true;}editor.setSelection(editor.length());scheduleHighlight();refreshTabs();}
 private void refreshTabs(){tabs.removeAllViews();for(final DocumentTab d:docs){TextView t=button(d.name()+"  ×");t.setBackgroundColor(d==active?Color.rgb(125,82,57):Color.rgb(155,120,95));t.setOnClickListener(new View.OnClickListener(){public void onClick(View v){bind(d);}});t.setOnLongClickListener(new View.OnLongClickListener(){public boolean onLongClick(View v){close(d);return true;}});tabs.addView(t,new LinearLayout.LayoutParams(-2,44));}}
 private void close(final DocumentTab d){if(d.dirty){new AlertDialog.Builder(this).setMessage("Guardar cambios en "+d.file.getName()+"?").setPositiveButton("GUARDAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface x,int w){if(save(d))closeAfterConversation(d);}}).setNegativeButton("DESCARTAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface x,int w){closeAfterConversation(d);}}).setNeutralButton("CANCELAR",null).show();}else closeAfterConversation(d);}
 private void remove(DocumentTab d){int i=docs.indexOf(d);docs.remove(d);active=null;if(!docs.isEmpty())bind(docs.get(Math.max(0,i-1)));else{binding=true;editor.setText("");binding=false;refreshTabs();updateStatus();}}
 private boolean save(DocumentTab d){if(d==null)return false;try{if(d==active)d.text=editor.getText().toString();FileUtils.write(d.file,d.text);d.dirty=false;refreshTabs();toast("Guardado: "+d.file.getName());return true;}catch(Exception e){error(e);return false;}}
 private void exportZip(){final EditText path=new EditText(this);File base=currentDir==null?workspace:currentDir;while(base.getParentFile()!=null&&!base.getParentFile().equals(workspace)&&base.getAbsolutePath().startsWith(workspace.getAbsolutePath()))base=base.getParentFile();final File project=base;path.setText("/sdcard/"+project.getName()+"_editado.zip");new AlertDialog.Builder(this).setTitle("Exportar ZIP a").setView(path).setPositiveButton("EXPORTAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){try{for(DocumentTab x:docs)save(x);FileUtils.zip(project,new File(path.getText().toString()));toast("ZIP exportado");offerConversationSave(null);}catch(Exception e){error(e);}}}).setNegativeButton("CANCELAR",null).show();}
 private Uri shareUri(File f){return new Uri.Builder().scheme("content").authority(getPackageName()+".files").appendPath("file").appendQueryParameter("path",f.getAbsolutePath()).build();}
 private void shareActive(boolean openWith){if(active==null){toast("Abre un archivo primero");return;}try{save(active);Intent i=new Intent(openWith?Intent.ACTION_VIEW:Intent.ACTION_SEND);Uri u=shareUri(active.file);String mime=mimeFor(active.file);i.setType(mime);if(openWith)i.setDataAndType(u,mime);else i.putExtra(Intent.EXTRA_STREAM,u);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);startActivity(Intent.createChooser(i,openWith?"Abrir código con":"Compartir archivo"));}catch(Exception e){error(e);}}
 private void shareProjectZip(){try{for(DocumentTab x:docs)save(x);File project=projectRoot;if(project==null||!project.exists())project=currentDir==null?workspace:currentDir;File out=new File(getExternalCacheDir(),project.getName()+"_editado.zip");FileUtils.zip(project,out);Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/zip");i.putExtra(Intent.EXTRA_STREAM,shareUri(out));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Enviar proyecto ZIP"));}catch(Exception e){error(e);}}
 private String mimeFor(File f){String x=extension(f).toLowerCase();if(x.equals("c")||x.equals("h"))return "text/x-csrc";if(x.equals("cpp")||x.equals("cc")||x.equals("hpp"))return "text/x-c++src";if(x.equals("java"))return "text/x-java";if(x.equals("py"))return "text/x-python";if(x.equals("zip"))return "application/zip";return "text/plain";}
 private void findText(){final EditText q=new EditText(this);new AlertDialog.Builder(this).setTitle("Buscar texto").setView(q).setPositiveButton("BUSCAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){int from=Math.max(0,editor.getSelectionEnd());int at=editor.getText().toString().indexOf(q.getText().toString(),from);if(at<0)at=editor.getText().toString().indexOf(q.getText().toString());if(at>=0)editor.setSelection(at,at+q.length());else toast("No encontrado");}}).show();}
 private void askAI(){if(active==null){toast("Abre un archivo primero");return;}final String question=aiInput.getText().toString().trim();if(question.length()==0)return;android.content.SharedPreferences sp=getSharedPreferences(SettingsActivity.PREF,0);String url=sp.getString(SettingsActivity.URL,"");String header=sp.getString(SettingsActivity.HEADER,"X-RetroAI-Key"),secret=sp.getString(SettingsActivity.SECRET,""),model=sp.getString(SettingsActivity.MODEL,"openrouter/free");if(url.length()==0){toast("Configura la URL de Render");return;}cancelAi(null);int a=editor.getSelectionStart(),b=editor.getSelectionEnd();final boolean selected=a!=b;final String code=selected?editor.getText().subSequence(Math.min(a,b),Math.max(a,b)).toString():editor.getText().toString();final String fileName=active.file.getName(),lang=extension(active.file),scope=selected?"selección":"archivo completo";final int sequence=++aiSequence;aiInput.setText("");updateAiScope();final String marker="Oliver IA ["+sequence+"]: consultando…";String contextRecord="\nProyecto: "+(projectRoot==null?"Archivo independiente":projectRoot.getName())+"\nArchivo: "+fileName+"\nContexto README:\n"+projectContext+"\n";if(!contextRecord.equals(lastContextRecord)){conversationContexts+=contextRecord;lastContextRecord=contextRecord;}aiHistory.append("\nTú ("+scope+"): "+question+"\n"+marker+"\n");scrollAi();aiRequest=AIClient.ask(url,header,secret,model,question,lang,fileName,code,projectContext,devMode,new AIClient.Callback(){public void done(final String ans,final Exception e){runOnUiThread(new Runnable(){public void run(){if(sequence!=aiSequence)return;aiRequest=null;replaceAiMarker(marker,"Oliver IA: "+(e==null?ans:friendlyAiError(e)));}});}});handler.postDelayed(new Runnable(){public void run(){if(sequence==aiSequence&&aiRequest!=null){aiRequest.cancel();aiRequest=null;replaceAiMarker(marker,"Oliver IA: la consulta tardó demasiado. Revisa la conexión e inténtalo nuevamente.");}}},95000);}
 private void replaceAiMarker(String marker,String replacement){String old=aiHistory.getText().toString();aiHistory.setText(old.replace(marker,replacement));scrollAi();}
 private void cancelAi(String message){if(aiRequest!=null){aiRequest.cancel();aiRequest=null;replaceAiMarker("Oliver IA ["+aiSequence+"]: consultando…",message==null?"Consulta reemplazada.":message);aiSequence++;}}
 private String friendlyAiError(Exception e){String s=String.valueOf(e.getMessage());if(s.indexOf("401")>=0)return "Clave incorrecta. Revisa APP_SHARED_KEY.";if(s.indexOf("SSL")>=0||s.indexOf("handshake")>=0)return "No se pudo establecer HTTPS. Verifica conexión y Google Play Services.";return "Error: "+s;}
 private void scrollAi(){aiScroll.post(new Runnable(){public void run(){aiScroll.fullScroll(View.FOCUS_DOWN);}});}
 private void scheduleHighlight(){if(highlightTask!=null)handler.removeCallbacks(highlightTask);highlightTask=new Runnable(){public void run(){if(active!=null){int p=editor.getSelectionStart(),end=editor.getSelectionEnd();binding=true;SyntaxHighlighter.apply(editor.getText(),active.file);binding=false;try{editor.setSelection(Math.max(0,Math.min(p,editor.length())),Math.max(0,Math.min(end,editor.length())));}catch(Exception ignored){}}}};handler.postDelayed(highlightTask,450);}
 private void updateStatus(){if(active==null){status.setText("Sin archivo");return;}int p=editor.getSelectionStart(),line=1,col=1;String s=editor.getText().toString();for(int i=0;i<p&&i<s.length();i++){if(s.charAt(i)=='\n'){line++;col=1;}else col++;}status.setText("Ln "+line+" : Col "+col+"    "+extension(active.file).toUpperCase());}
 private String extension(File f){String n=f.getName();int p=n.lastIndexOf('.');return p>=0?n.substring(p+1):"txt";}private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}private void error(Exception e){new AlertDialog.Builder(this).setTitle("Error").setMessage(e.getMessage()).setPositiveButton("ACEPTAR",null).show();}
 @Override protected void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);try{out.putString("taskSnapshot",saveTaskSnapshot().getAbsolutePath());}catch(Exception ignored){}}
 private void writeString(DataOutputStream o,String s)throws IOException{byte[] b=(s==null?"":s).getBytes("UTF-8");o.writeInt(b.length);o.write(b);}
 private String readString(DataInputStream in)throws IOException{int n=in.readInt();if(n<0||n>12*1024*1024)throw new IOException("Sesión dañada");byte[] b=new byte[n];in.readFully(b);return new String(b,"UTF-8");}
 private File saveTaskSnapshot()throws IOException{if(active!=null){active.text=editor.getText().toString();active.cursor=editor.getSelectionStart();}File f=new File(getCacheDir(),"open-task.session");DataOutputStream o=new DataOutputStream(new BufferedOutputStream(new FileOutputStream(f)));o.writeInt(2);writeString(o,conversationContexts);writeString(o,savedConversation);writeString(o,currentDir==null?"":currentDir.getAbsolutePath());writeString(o,projectRoot==null?"":projectRoot.getAbsolutePath());o.writeBoolean(readOnly);o.writeBoolean(sideVisible);writeString(o,aiHistory.getText().toString());o.writeInt(aiPanelSize);o.writeBoolean(devMode);o.writeInt(docs.indexOf(active));o.writeInt(docs.size());for(DocumentTab d:docs){writeString(o,d.file.getAbsolutePath());writeString(o,d.text);o.writeInt(d.cursor);o.writeBoolean(d.dirty);}o.close();return f;}
 private void restoreSession(Bundle state){DataInputStream in=null;try{String p=state.getString("taskSnapshot");if(p==null)throw new IOException("Sin sesión");in=new DataInputStream(new BufferedInputStream(new FileInputStream(p)));if(in.readInt()!=2)throw new IOException("Sesión incompatible");conversationContexts=readString(in);savedConversation=readString(in);String cd=readString(in),pr=readString(in);currentDir=cd.length()==0?workspace:new File(cd);projectRoot=pr.length()==0?null:new File(pr);readOnly=in.readBoolean();sideVisible=in.readBoolean();String history=readString(in);aiPanelSize=in.readInt();devMode=in.readBoolean();int at=in.readInt(),count=in.readInt();for(int i=0;i<count;i++){File f=new File(readString(in));String text=readString(in);int cursor=in.readInt();boolean dirty=in.readBoolean();if(!f.exists())continue;DocumentTab d=new DocumentTab(f,text);d.cursor=cursor;d.dirty=dirty;docs.add(d);}in.close();if(projectRoot!=null)projectContext=getSharedPreferences("contexts",0).getString(projectRoot.getAbsolutePath(),"");showFiles(currentDir.exists()?currentDir:workspace);if(!docs.isEmpty())bind(docs.get(Math.max(0,Math.min(at,docs.size()-1))));setReadOnly(readOnly);side.setVisibility(sideVisible?View.VISIBLE:View.GONE);aiHistory.setText(history.replace("consultando…","consulta interrumpida; puedes reenviarla."));devButton.setText(devMode?"DEV":"NORMAL");int[] heights={150,260,400};android.view.ViewGroup.LayoutParams lp=aiPanel.getLayoutParams();lp.height=dp(heights[Math.max(0,Math.min(aiPanelSize,2))]);aiPanel.setLayoutParams(lp);}catch(Exception e){try{if(in!=null)in.close();}catch(Exception ignored){}docs.clear();showHome();}}
 @Override public void onBackPressed(){if(aiPanel.getVisibility()==View.VISIBLE){requestCloseChat();return;}try{saveTaskSnapshot();}catch(Exception ignored){}moveTaskToBack(true);}

 private void showQuestions(View anchor){
  final String[] questions={"¿Qué hace este código?","Explícalo paso a paso sin reescribirlo","Explícalo para principiantes","¿Hay errores? Explica sin generar código","¿Qué podría mejorar?","Dame el código corregido"};
  PopupMenu menu=new PopupMenu(this,anchor);
  for(int i=0;i<questions.length;i++)menu.getMenu().add(0,i,i,questions[i]);
  menu.getMenu().add(0,100,100,"Guardar conversación TXT");
  menu.setOnMenuItemClickListener(new PopupMenu.OnMenuItemClickListener(){public boolean onMenuItemClick(MenuItem item){if(item.getItemId()==100){saveConversationManually();return true;}aiInput.setText(questions[item.getItemId()]);aiInput.setSelection(aiInput.length());return true;}});
  menu.show();
 }
 private void hideChat(){aiPanel.setVisibility(View.GONE);((android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(aiInput.getWindowToken(),0);}
 private void requestCloseChat(){hideChat();}
 private void offerConversationSave(final Runnable after){
  if(chatClosePrompt)return;
  final String transcript=aiHistory.getText().toString();
  if(transcript.indexOf("Tú (")<0||transcript.equals(savedConversation)){
   if(after!=null)after.run();return;
  }
  chatClosePrompt=true;
  AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Guardar conversación TXT")
   .setMessage("¿Quieres guardar también la conversación en workspaces/Conversaciones IA?"+(aiRequest!=null?" La respuesta pendiente no se incluirá hasta que termine.":""))
   .setPositiveButton("GUARDAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){
    if(saveConversation()){savedConversation=aiHistory.getText().toString();if(after!=null)after.run();}
   }})
   .setNegativeButton("NO GUARDAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){
    savedConversation=aiHistory.getText().toString();if(after!=null)after.run();
   }})
   .setNeutralButton("CANCELAR",null).create();
  dialog.setOnDismissListener(new DialogInterface.OnDismissListener(){public void onDismiss(DialogInterface d){chatClosePrompt=false;}});
  dialog.show();
 }
 private void saveConversationManually(){
  if(aiHistory.getText().toString().indexOf("Tú (")<0){toast("Todavía no hay conversación para guardar");return;}
  if(saveConversation())savedConversation=aiHistory.getText().toString();
 }
 private void closeAfterConversation(final DocumentTab doc){
  offerConversationSave(new Runnable(){public void run(){remove(doc);}});
 }
 private boolean saveConversation(){
  try{
   String name=projectRoot==null?(active==null?"Sin proyecto":active.file.getName()):projectRoot.getName();
   String date=new java.text.SimpleDateFormat("yyyy-MM-dd_HH-mm-ss",java.util.Locale.US).format(new java.util.Date());
   File folder=new File(workspace,"Conversaciones IA");folder.mkdirs();
   File file=File.createTempFile("chat_"+name.replaceAll("[^\\p{L}\\p{N}._-]","_")+"_"+date+"_",".txt",folder);
   String header="OliverCode Lite · Conversación IA\nProyecto al guardar: "+name+"\nFecha: "+date+"\nModo: "+(devMode?"Dev":"Normal")+"\n\nCONTEXTOS DE PROYECTO Y ARCHIVO\n";
   FileUtils.write(file,header+conversationContexts+"\nCONVERSACIÓN EN BRUTO\n\n"+aiHistory.getText().toString());
   toast("Guardada en workspaces/Conversaciones IA");return true;
  }catch(Exception e){error(e);return false;}
 }
}
