package cl.will.codepadai;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.ColorDrawable;import android.text.*;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity {
 private LinearLayout root,side,tabs; private EditText editor; private TextView status; private ListView browser; private File workspace,currentDir; private final ArrayList<DocumentTab> docs=new ArrayList<DocumentTab>(); private DocumentTab active; private boolean binding,sideVisible=true; private Handler handler=new Handler(); private Runnable highlightTask;
 private int brown=Color.rgb(100,65,45), cream=Color.rgb(250,248,244); private final ArrayDeque<String> undo=new ArrayDeque<String>(), redo=new ArrayDeque<String>();

 public void onCreate(Bundle b){super.onCreate(b); workspace=new File(getExternalFilesDir(null),"workspaces");workspace.mkdirs(); buildUi(); showHome();}
 private TextView button(String text){TextView v=new TextView(this);v.setText(text);v.setTextColor(Color.WHITE);v.setGravity(Gravity.CENTER);v.setPadding(12,8,12,8);v.setBackgroundColor(brown);return v;}
 private void buildUi(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(cream);
  LinearLayout top=new LinearLayout(this); top.setGravity(Gravity.CENTER_VERTICAL); TextView menu=button("☰");top.addView(menu,new LinearLayout.LayoutParams(52,44)); HorizontalScrollView tabScroll=new HorizontalScrollView(this);tabs=new LinearLayout(this);tabScroll.addView(tabs);top.addView(tabScroll,new LinearLayout.LayoutParams(0,44,1));TextView more=button("⋮");top.addView(more,new LinearLayout.LayoutParams(48,44));root.addView(top);
  LinearLayout body=new LinearLayout(this);side=new LinearLayout(this);side.setOrientation(LinearLayout.VERTICAL);side.setBackgroundColor(Color.rgb(235,229,222));
  LinearLayout modes=new LinearLayout(this);TextView project=button("PROYECTO"), symbols=button("SÍMBOLOS");modes.addView(project,new LinearLayout.LayoutParams(0,38,1));modes.addView(symbols,new LinearLayout.LayoutParams(0,38,1));side.addView(modes);browser=new ListView(this);side.addView(browser,new LinearLayout.LayoutParams(-1,0,1));body.addView(side,new LinearLayout.LayoutParams(dp(185),-1));
  editor=new EditText(this);editor.setGravity(Gravity.TOP|Gravity.LEFT);editor.setTextSize(14);editor.setTextColor(Color.rgb(40,40,40));editor.setBackgroundColor(Color.WHITE);editor.setTypeface(Typeface.MONOSPACE);editor.setPadding(10,8,10,8);editor.setHorizontallyScrolling(true);editor.setSingleLine(false);editor.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE|android.text.InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);body.addView(editor,new LinearLayout.LayoutParams(0,-1,1));root.addView(body,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout bottom=new LinearLayout(this);status=new TextView(this);status.setText("Sin archivo");status.setPadding(10,6,4,6);bottom.addView(status,new LinearLayout.LayoutParams(0,36,1));TextView ai=button("🤖 IA");bottom.addView(ai,new LinearLayout.LayoutParams(76,36));root.addView(bottom);setContentView(root);
  menu.setOnClickListener(new View.OnClickListener(){public void onClick(View v){sideVisible=!sideVisible;side.setVisibility(sideVisible?View.VISIBLE:View.GONE);}});more.setOnClickListener(new View.OnClickListener(){public void onClick(View v){showMenu(v);}});project.setOnClickListener(new View.OnClickListener(){public void onClick(View v){showFiles(currentDir==null?workspace:currentDir);}});symbols.setOnClickListener(new View.OnClickListener(){public void onClick(View v){showSymbols();}});ai.setOnClickListener(new View.OnClickListener(){public void onClick(View v){askAI();}});
  editor.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){if(!binding&&active!=null){undo.addLast(s.toString());while(undo.size()>40)undo.removeFirst();redo.clear();}}public void onTextChanged(CharSequence s,int st,int b,int c){if(binding||active==null)return;active.text=s.toString();active.dirty=true;active.cursor=editor.getSelectionStart();refreshTabs();scheduleHighlight();updateStatus();}public void afterTextChanged(Editable e){}});
 }
 private void showMenu(View anchor){PopupMenu p=new PopupMenu(this,anchor);p.getMenu().add("Abrir archivo");p.getMenu().add("Abrir proyecto ZIP");p.getMenu().add("Archivo nuevo");p.getMenu().add("Guardar");p.getMenu().add("Guardar todos");p.getMenu().add("Exportar proyecto ZIP");p.getMenu().add("Buscar");p.getMenu().add("Deshacer");p.getMenu().add("Rehacer");p.getMenu().add("Ajustes");p.setOnMenuItemClickListener(new PopupMenu.OnMenuItemClickListener(){public boolean onMenuItemClick(android.view.MenuItem i){String s=i.getTitle().toString();if(s.equals("Abrir archivo"))chooseFile(false);else if(s.equals("Abrir proyecto ZIP"))chooseFile(true);else if(s.equals("Archivo nuevo"))newFile();else if(s.equals("Guardar"))save(active);else if(s.equals("Guardar todos"))for(DocumentTab d:docs)save(d);else if(s.equals("Exportar proyecto ZIP"))exportZip();else if(s.equals("Buscar"))findText();else if(s.equals("Deshacer"))undo();else if(s.equals("Rehacer"))redo();else startActivity(new Intent(MainActivity.this,SettingsActivity.class));return true;}});p.show();}
 private void showHome(){currentDir=workspace;showFiles(workspace);}
 private void showFiles(final File dir){currentDir=dir;final ArrayList<File> fs=new ArrayList<File>();if(dir.getParentFile()!=null&&dir.getAbsolutePath().startsWith(workspace.getAbsolutePath()))fs.add(dir.getParentFile());File[] a=dir.listFiles();if(a!=null){Arrays.sort(a,new Comparator<File>(){public int compare(File x,File y){if(x.isDirectory()!=y.isDirectory())return x.isDirectory()?-1:1;return x.getName().compareToIgnoreCase(y.getName());}});for(File f:a)fs.add(f);}ArrayList<String> names=new ArrayList<String>();for(File f:fs)names.add(f.equals(dir.getParentFile())?"↰ ..":(f.isDirectory()?"▸ ":"  ")+f.getName());browser.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,names));browser.setOnItemClickListener(new android.widget.AdapterView.OnItemClickListener(){public void onItemClick(android.widget.AdapterView<?> a,View v,int pos,long id){File f=fs.get(pos);if(f.isDirectory())showFiles(f);else openFile(f);}});}
 private void showSymbols(){final java.util.List<SymbolScanner.Symbol> ss=active==null?new ArrayList<SymbolScanner.Symbol>():SymbolScanner.scan(editor.getText().toString());browser.setAdapter(new ArrayAdapter<SymbolScanner.Symbol>(this,android.R.layout.simple_list_item_1,ss));browser.setOnItemClickListener(new android.widget.AdapterView.OnItemClickListener(){public void onItemClick(android.widget.AdapterView<?> a,View v,int p,long id){int o=ss.get(p).offset;editor.setSelection(Math.min(o,editor.length()));editor.requestFocus();}});}
 private void chooseFile(final boolean zip){final EditText path=new EditText(this);path.setText("/sdcard/");new AlertDialog.Builder(this).setTitle(zip?"Ruta del proyecto ZIP":"Ruta del archivo").setView(path).setPositiveButton("ABRIR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){File f=new File(path.getText().toString());if(zip)importZip(f);else openFile(f);}}).setNegativeButton("CANCELAR",null).show();}
 private void importZip(final File zip){try{String n=zip.getName().replaceAll("(?i)\\.zip$","")+"_"+System.currentTimeMillis();File out=new File(workspace,n);out.mkdirs();FileUtils.unzip(zip,out);showFiles(out);toast("Proyecto importado");}catch(Exception e){error(e);}}
 private void openFile(File f){if(!f.isFile()){toast("No existe el archivo");return;}for(DocumentTab d:docs)if(d.file.equals(f)){bind(d);return;}try{if(f.length()>2*1024*1024){toast("Archivo demasiado grande para esta versión");return;}DocumentTab d=new DocumentTab(f,FileUtils.read(f));docs.add(d);bind(d);}catch(Exception e){error(e);}}
 private void newFile(){final EditText name=new EditText(this);name.setHint("NuevoArchivo.java");new AlertDialog.Builder(this).setTitle("Nuevo archivo").setView(name).setPositiveButton("CREAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){try{File dir=currentDir!=null&&currentDir.isDirectory()?currentDir:workspace;File f=new File(dir,name.getText().toString().trim());FileUtils.write(f,"");openFile(f);showFiles(dir);}catch(Exception e){error(e);}}}).setNegativeButton("CANCELAR",null).show();}
 private void bind(DocumentTab d){if(active!=null)active.cursor=editor.getSelectionStart();active=d;undo.clear();redo.clear();binding=true;editor.setText(d.text);editor.setSelection(Math.min(d.cursor,editor.length()));binding=false;SyntaxHighlighter.apply(editor.getText(),d.file);refreshTabs();updateStatus();}
 private void undo(){if(undo.isEmpty())return;redo.addLast(editor.getText().toString());setHistoryText(undo.removeLast());}
 private void redo(){if(redo.isEmpty())return;undo.addLast(editor.getText().toString());setHistoryText(redo.removeLast());}
 private void setHistoryText(String s){binding=true;editor.setText(s);binding=false;if(active!=null){active.text=s;active.dirty=true;}editor.setSelection(editor.length());scheduleHighlight();refreshTabs();}
 private void refreshTabs(){tabs.removeAllViews();for(final DocumentTab d:docs){TextView t=button(d.name()+"  ×");t.setBackgroundColor(d==active?Color.rgb(125,82,57):Color.rgb(155,120,95));t.setOnClickListener(new View.OnClickListener(){public void onClick(View v){bind(d);}});t.setOnLongClickListener(new View.OnLongClickListener(){public boolean onLongClick(View v){close(d);return true;}});tabs.addView(t,new LinearLayout.LayoutParams(-2,44));}}
 private void close(final DocumentTab d){if(d.dirty){new AlertDialog.Builder(this).setMessage("Guardar cambios en "+d.file.getName()+"?").setPositiveButton("GUARDAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface x,int w){save(d);remove(d);}}).setNegativeButton("DESCARTAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface x,int w){remove(d);}}).setNeutralButton("CANCELAR",null).show();}else remove(d);}
 private void remove(DocumentTab d){int i=docs.indexOf(d);docs.remove(d);active=null;if(!docs.isEmpty())bind(docs.get(Math.max(0,i-1)));else{binding=true;editor.setText("");binding=false;refreshTabs();updateStatus();}}
 private void save(DocumentTab d){if(d==null)return;try{if(d==active)d.text=editor.getText().toString();FileUtils.write(d.file,d.text);d.dirty=false;refreshTabs();toast("Guardado: "+d.file.getName());}catch(Exception e){error(e);}}
 private void exportZip(){final EditText path=new EditText(this);File base=currentDir==null?workspace:currentDir;while(base.getParentFile()!=null&&!base.getParentFile().equals(workspace)&&base.getAbsolutePath().startsWith(workspace.getAbsolutePath()))base=base.getParentFile();final File project=base;path.setText("/sdcard/"+project.getName()+"_editado.zip");new AlertDialog.Builder(this).setTitle("Exportar ZIP a").setView(path).setPositiveButton("EXPORTAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){try{for(DocumentTab x:docs)save(x);FileUtils.zip(project,new File(path.getText().toString()));toast("ZIP exportado");}catch(Exception e){error(e);}}}).setNegativeButton("CANCELAR",null).show();}
 private void findText(){final EditText q=new EditText(this);new AlertDialog.Builder(this).setTitle("Buscar texto").setView(q).setPositiveButton("BUSCAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){int from=Math.max(0,editor.getSelectionEnd());int at=editor.getText().toString().indexOf(q.getText().toString(),from);if(at<0)at=editor.getText().toString().indexOf(q.getText().toString());if(at>=0)editor.setSelection(at,at+q.length());else toast("No encontrado");}}).show();}
 private void askAI(){if(active==null){toast("Abre un archivo primero");return;}final EditText q=new EditText(this);q.setHint("¿Qué quieres preguntar?");new AlertDialog.Builder(this).setTitle("Preguntar a IA").setView(q).setPositiveButton("ENVIAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){String url=getSharedPreferences(SettingsActivity.PREF,0).getString(SettingsActivity.URL,"");if(url.length()==0){toast("Configura la URL del backend");return;}int a=editor.getSelectionStart(),b=editor.getSelectionEnd();final String code=a!=b?editor.getText().subSequence(Math.min(a,b),Math.max(a,b)).toString():editor.getText().toString();final ProgressDialog pd=ProgressDialog.show(MainActivity.this,"IA","Consultando…",true,false);AIClient.ask(url,q.getText().toString(),extension(active.file),active.file.getName(),code,new AIClient.Callback(){public void done(final String ans,final Exception e){runOnUiThread(new Runnable(){public void run(){pd.dismiss();if(e!=null)error(e);else new AlertDialog.Builder(MainActivity.this).setTitle("Respuesta IA").setMessage(ans).setPositiveButton("CERRAR",null).setNeutralButton("COPIAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("IA",ans));}}).show();}});}});}}).setNegativeButton("CANCELAR",null).show();}
 private void scheduleHighlight(){if(highlightTask!=null)handler.removeCallbacks(highlightTask);highlightTask=new Runnable(){public void run(){if(active!=null){int p=editor.getSelectionStart();binding=true;SyntaxHighlighter.apply(editor.getText(),active.file);binding=false;try{editor.setSelection(Math.min(p,editor.length()));}catch(Exception ignored){}}}};handler.postDelayed(highlightTask,450);}
 private void updateStatus(){if(active==null){status.setText("Sin archivo");return;}int p=editor.getSelectionStart(),line=1,col=1;String s=editor.getText().toString();for(int i=0;i<p&&i<s.length();i++){if(s.charAt(i)=='\n'){line++;col=1;}else col++;}status.setText("Ln "+line+" : Col "+col+"    "+extension(active.file).toUpperCase());}
 private String extension(File f){String n=f.getName();int p=n.lastIndexOf('.');return p>=0?n.substring(p+1):"txt";}private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}private void error(Exception e){new AlertDialog.Builder(this).setTitle("Error").setMessage(e.getMessage()).setPositiveButton("ACEPTAR",null).show();}
 @Override public void onBackPressed(){if(active!=null&&active.dirty){close(active);}else super.onBackPressed();}
}
