package cl.will.codepadai;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.text.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity {
 private static final int PICK_FILE=41,PICK_ZIP=42; private LinearLayout root,side,tabs,aiPanel; private CodeEditText editor; private LineNumberView lineNumbers; private TextView status,aiHistory,aiSizeButton; private EditText aiInput; private ScrollView aiScroll; private ListView browser; private File workspace,currentDir,projectRoot; private String projectContext=""; private final ArrayList<DocumentTab> docs=new ArrayList<DocumentTab>(); private final HashSet<String> contextAttempts=new HashSet<String>(); private DocumentTab active; private boolean binding,sideVisible=true,wrapLines=false; private int aiPanelSize=0; private Handler handler=new Handler(); private Runnable highlightTask;
 private int brown=Color.rgb(100,65,45), cream=Color.rgb(250,248,244); private final ArrayDeque<String> undo=new ArrayDeque<String>(), redo=new ArrayDeque<String>();

 public void onCreate(Bundle b){super.onCreate(b); workspace=new File(getExternalFilesDir(null),"workspaces");workspace.mkdirs();wrapLines=getSharedPreferences("editor",0).getBoolean("wrap",false);buildUi();showHome();}
 private TextView button(String text){TextView v=new TextView(this);v.setText(text);v.setTextColor(Color.WHITE);v.setGravity(Gravity.CENTER);v.setPadding(12,8,12,8);v.setBackgroundColor(brown);return v;}
 private void buildUi(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(cream);
  LinearLayout top=new LinearLayout(this); top.setGravity(Gravity.CENTER_VERTICAL); TextView menu=button("☰");top.addView(menu,new LinearLayout.LayoutParams(52,44)); HorizontalScrollView tabScroll=new HorizontalScrollView(this);tabs=new LinearLayout(this);tabScroll.addView(tabs);top.addView(tabScroll,new LinearLayout.LayoutParams(0,44,1));TextView more=button("⋮");top.addView(more,new LinearLayout.LayoutParams(48,44));root.addView(top);
  LinearLayout body=new LinearLayout(this);side=new LinearLayout(this);side.setOrientation(LinearLayout.VERTICAL);side.setBackgroundColor(Color.rgb(235,229,222));
  LinearLayout modes=new LinearLayout(this);TextView project=button("PROYECTO"), symbols=button("SÍMBOLOS");modes.addView(project,new LinearLayout.LayoutParams(0,38,1));modes.addView(symbols,new LinearLayout.LayoutParams(0,38,1));side.addView(modes);browser=new ListView(this);side.addView(browser,new LinearLayout.LayoutParams(-1,0,1));body.addView(side,new LinearLayout.LayoutParams(dp(185),-1));
  LinearLayout codeArea=new LinearLayout(this);lineNumbers=new LineNumberView(this);editor=new CodeEditText(this);lineNumbers.attach(editor);codeArea.addView(lineNumbers,new LinearLayout.LayoutParams(dp(46),-1));editor.setGravity(Gravity.TOP|Gravity.LEFT);editor.setTextSize(14);editor.setTextColor(Color.rgb(40,40,40));editor.setBackgroundColor(Color.WHITE);editor.setTypeface(Typeface.MONOSPACE);editor.setPadding(10,8,10,8);editor.setSingleLine(false);editor.setHorizontallyScrolling(!wrapLines);editor.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE|android.text.InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);codeArea.addView(editor,new LinearLayout.LayoutParams(0,-1,1));body.addView(codeArea,new LinearLayout.LayoutParams(0,-1,1));root.addView(body,new LinearLayout.LayoutParams(-1,0,1));
  buildAiPanel();root.addView(aiPanel,new LinearLayout.LayoutParams(-1,dp(150)));aiPanel.setVisibility(View.GONE);
  LinearLayout bottom=new LinearLayout(this);status=new TextView(this);status.setText("Sin archivo");status.setPadding(10,6,4,6);bottom.addView(status,new LinearLayout.LayoutParams(0,36,1));TextView ai=button("IA");bottom.addView(ai,new LinearLayout.LayoutParams(76,36));root.addView(bottom);
  FrameLayout stage=new FrameLayout(this);stage.addView(root,new FrameLayout.LayoutParams(-1,-1));stage.addView(makeSymbolPalette());setContentView(stage);
  menu.setOnClickListener(new View.OnClickListener(){public void onClick(View v){sideVisible=!sideVisible;side.setVisibility(sideVisible?View.VISIBLE:View.GONE);}});more.setOnClickListener(new View.OnClickListener(){public void onClick(View v){showMenu(v);}});project.setOnClickListener(new View.OnClickListener(){public void onClick(View v){showFiles(currentDir==null?workspace:currentDir);}});symbols.setOnClickListener(new View.OnClickListener(){public void onClick(View v){showSymbols();}});ai.setOnClickListener(new View.OnClickListener(){public void onClick(View v){if(active==null){toast("Abre un archivo primero");return;}aiPanel.setVisibility(aiPanel.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE);}});
  editor.getViewTreeObserver().addOnScrollChangedListener(new ViewTreeObserver.OnScrollChangedListener(){public void onScrollChanged(){lineNumbers.invalidate();}});editor.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){if(!binding&&active!=null){undo.addLast(s.toString());while(undo.size()>40)undo.removeFirst();redo.clear();}}public void onTextChanged(CharSequence s,int st,int b,int c){lineNumbers.invalidate();if(binding||active==null)return;active.text=s.toString();active.dirty=true;active.cursor=editor.getSelectionStart();refreshTabs();scheduleHighlight();updateStatus();}public void afterTextChanged(Editable e){}});
 }
 private void buildAiPanel(){aiPanel=new LinearLayout(this);aiPanel.setOrientation(LinearLayout.VERTICAL);aiPanel.setPadding(dp(6),dp(4),dp(6),dp(4));aiPanel.setBackgroundColor(Color.rgb(239,233,226));LinearLayout title=new LinearLayout(this);TextView label=new TextView(this);label.setText("Oliver IA"+(projectContext.length()>0?" · README ✓":""));label.setTextColor(brown);label.setTextSize(16);title.addView(label,new LinearLayout.LayoutParams(0,dp(28),1));aiSizeButton=button("MED");title.addView(aiSizeButton,new LinearLayout.LayoutParams(dp(52),dp(28)));TextView close=button("×");title.addView(close,new LinearLayout.LayoutParams(dp(40),dp(28)));aiPanel.addView(title);aiHistory=new TextView(this);aiHistory.setText("Pregunta sobre el archivo activo sin dejar de ver el código.\n");aiHistory.setTextIsSelectable(true);aiHistory.setTextColor(Color.DKGRAY);aiScroll=new ScrollView(this);aiScroll.addView(aiHistory);aiPanel.addView(aiScroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout sendRow=new LinearLayout(this);aiInput=new EditText(this);aiInput.setHint("Pregunta sobre este código…");aiInput.setSingleLine();sendRow.addView(aiInput,new LinearLayout.LayoutParams(0,dp(42),1));TextView send=button("ENVIAR");sendRow.addView(send,new LinearLayout.LayoutParams(dp(82),dp(42)));aiPanel.addView(sendRow);aiSizeButton.setOnClickListener(new View.OnClickListener(){public void onClick(View v){cycleAiPanelSize();}});close.setOnClickListener(new View.OnClickListener(){public void onClick(View v){aiPanel.setVisibility(View.GONE);}});send.setOnClickListener(new View.OnClickListener(){public void onClick(View v){askAI();}});}
 private void cycleAiPanelSize(){aiPanelSize=(aiPanelSize+1)%3;int[] heights={150,260,400};String[] next={"MED","GRANDE","PEQ"};android.view.ViewGroup.LayoutParams lp=aiPanel.getLayoutParams();lp.height=dp(heights[aiPanelSize]);aiPanel.setLayoutParams(lp);aiSizeButton.setText(next[aiPanelSize]);}
 private View makeSymbolPalette(){final LinearLayout bar=new LinearLayout(this);bar.setPadding(2,2,2,2);bar.setBackgroundColor(Color.rgb(72,52,43));final TextView handle=button("↕");bar.addView(handle,new LinearLayout.LayoutParams(dp(36),dp(38)));String[] keys={"\"","'",";",":","(",")","[","]","{","}","<",">","=","+","-","_","/","\\","|","&","!","?","."};for(final String k:keys){TextView b=button(k);b.setBackgroundColor(Color.rgb(110,78,60));b.setOnClickListener(new View.OnClickListener(){public void onClick(View v){insertSymbol(k);}});bar.addView(b,new LinearLayout.LayoutParams(dp(34),dp(38)));}HorizontalScrollView scroll=new HorizontalScrollView(this);scroll.setBackgroundColor(Color.rgb(72,52,43));scroll.addView(bar);final FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(dp(300),dp(42),Gravity.RIGHT|Gravity.TOP);lp.topMargin=dp(58);lp.rightMargin=dp(8);scroll.setLayoutParams(lp);handle.setOnTouchListener(new View.OnTouchListener(){float dx,dy;public boolean onTouch(View v,MotionEvent e){View parent=(View)v.getParent().getParent();if(e.getAction()==MotionEvent.ACTION_DOWN){dx=e.getRawX()-parent.getX();dy=e.getRawY()-parent.getY();return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){parent.setX(Math.max(0,e.getRawX()-dx));parent.setY(Math.max(0,e.getRawY()-dy));return true;}return true;}});return scroll;}
 private void insertSymbol(String s){if(active==null)return;int a=Math.max(0,editor.getSelectionStart()),b=Math.max(0,editor.getSelectionEnd());editor.getText().replace(Math.min(a,b),Math.max(a,b),s);editor.setSelection(Math.min(a,b)+s.length());editor.requestFocus();}
 private void showMenu(View anchor){PopupMenu p=new PopupMenu(this,anchor);p.getMenu().add("Abrir archivo");p.getMenu().add("Abrir proyecto ZIP");p.getMenu().add("Archivo nuevo");p.getMenu().add("Guardar");p.getMenu().add("Guardar todos");p.getMenu().add("Exportar proyecto ZIP");p.getMenu().add("Buscar");p.getMenu().add("Deshacer");p.getMenu().add("Rehacer");p.getMenu().add(wrapLines?"Desactivar ajuste de línea":"Activar ajuste de línea");p.getMenu().add("Ajustes");p.setOnMenuItemClickListener(new PopupMenu.OnMenuItemClickListener(){public boolean onMenuItemClick(android.view.MenuItem i){String s=i.getTitle().toString();if(s.equals("Abrir archivo"))chooseFile(false);else if(s.equals("Abrir proyecto ZIP"))chooseFile(true);else if(s.equals("Archivo nuevo"))newFile();else if(s.equals("Guardar"))save(active);else if(s.equals("Guardar todos"))for(DocumentTab d:docs)save(d);else if(s.equals("Exportar proyecto ZIP"))exportZip();else if(s.equals("Buscar"))findText();else if(s.equals("Deshacer"))undo();else if(s.equals("Rehacer"))redo();else if(s.indexOf("ajuste de línea")>=0)toggleWrap();else startActivity(new Intent(MainActivity.this,SettingsActivity.class));return true;}});p.show();}
 private void toggleWrap(){wrapLines=!wrapLines;editor.setHorizontallyScrolling(!wrapLines);editor.requestLayout();getSharedPreferences("editor",0).edit().putBoolean("wrap",wrapLines).apply();lineNumbers.invalidate();toast(wrapLines?"Ajuste de línea activado":"Ajuste de línea desactivado");}
 private void showHome(){currentDir=workspace;showFiles(workspace);}
 private void showFiles(final File dir){currentDir=dir;final ArrayList<File> fs=new ArrayList<File>();if(dir.getParentFile()!=null&&dir.getAbsolutePath().startsWith(workspace.getAbsolutePath()))fs.add(dir.getParentFile());File[] a=dir.listFiles();if(a!=null){Arrays.sort(a,new Comparator<File>(){public int compare(File x,File y){if(x.isDirectory()!=y.isDirectory())return x.isDirectory()?-1:1;return x.getName().compareToIgnoreCase(y.getName());}});for(File f:a)fs.add(f);}ArrayList<String> names=new ArrayList<String>();for(File f:fs)names.add(f.equals(dir.getParentFile())?"↰ ..":(f.isDirectory()?"▸ ":"  ")+f.getName());browser.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,names));browser.setOnItemClickListener(new android.widget.AdapterView.OnItemClickListener(){public void onItemClick(android.widget.AdapterView<?> a,View v,int pos,long id){File f=fs.get(pos);if(f.isDirectory()){if(f.getParentFile()!=null&&f.getParentFile().equals(workspace)){projectRoot=f;loadProjectContext(f);}showFiles(f);}else openFile(f);}});browser.setOnItemLongClickListener(new android.widget.AdapterView.OnItemLongClickListener(){public boolean onItemLongClick(android.widget.AdapterView<?> a,View v,int pos,long id){final File f=fs.get(pos);if(f.equals(dir.getParentFile()))return true;new AlertDialog.Builder(MainActivity.this).setTitle("Eliminar").setMessage("¿Desea eliminar "+f.getName()+"?").setPositiveButton("ELIMINAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){closeDeletedTabs(f);if(FileUtils.deleteRecursive(f)){showFiles(dir);toast("Eliminado");}else toast("No se pudo eliminar");}}).setNegativeButton("CANCELAR",null).show();return true;}});}
 private void closeDeletedTabs(File f){ArrayList<DocumentTab> copy=new ArrayList<DocumentTab>(docs);for(DocumentTab d:copy)if(d.file.getAbsolutePath().startsWith(f.getAbsolutePath())){docs.remove(d);if(active==d)active=null;}if(active==null){if(!docs.isEmpty())bind(docs.get(0));else{binding=true;editor.setText("");binding=false;refreshTabs();updateStatus();}}}
 private void showSymbols(){final java.util.List<SymbolScanner.Symbol> ss=active==null?new ArrayList<SymbolScanner.Symbol>():SymbolScanner.scan(editor.getText().toString());browser.setAdapter(new ArrayAdapter<SymbolScanner.Symbol>(this,android.R.layout.simple_list_item_1,ss));browser.setOnItemClickListener(new android.widget.AdapterView.OnItemClickListener(){public void onItemClick(android.widget.AdapterView<?> a,View v,int p,long id){int o=ss.get(p).offset;editor.setSelection(Math.min(o,editor.length()));editor.requestFocus();}});}
 private void chooseFile(final boolean zip){try{Intent i=new Intent(Intent.ACTION_GET_CONTENT);i.setType(zip?"application/zip":"*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(Intent.createChooser(i,zip?"Seleccionar proyecto ZIP":"Seleccionar archivo"),zip?PICK_ZIP:PICK_FILE);}catch(Exception e){toast("Instala o activa un administrador de archivos");}}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;try{Uri uri=data.getData();String name=fileName(uri,request==PICK_ZIP?"proyecto.zip":"archivo.txt");File picked=new File(getCacheDir(),name);InputStream in=getContentResolver().openInputStream(uri);FileOutputStream out=new FileOutputStream(picked);byte[] buf=new byte[8192];int n;while((n=in.read(buf))>0)out.write(buf,0,n);in.close();out.close();if(request==PICK_ZIP)importZip(picked);else{File dir=currentDir!=null&&currentDir.isDirectory()?currentDir:workspace;File copy=new File(dir,name);FileUtils.write(copy,FileUtils.read(picked));openFile(copy);showFiles(dir);}}catch(Exception e){error(e);}}
 private String fileName(Uri uri,String fallback){String n=null;android.database.Cursor c=null;try{c=getContentResolver().query(uri,new String[]{android.provider.OpenableColumns.DISPLAY_NAME},null,null,null);if(c!=null&&c.moveToFirst())n=c.getString(0);}catch(Exception ignored){}finally{if(c!=null)c.close();}if(n==null||n.length()==0)n=uri.getLastPathSegment();if(n==null||n.length()==0)n=fallback;int p=n.lastIndexOf('/');if(p>=0)n=n.substring(p+1);return n.replaceAll("[^A-Za-z0-9._() -]","_");}
 private void importZip(final File zip){try{String n=zip.getName().replaceAll("(?i)\\.zip$","")+"_"+System.currentTimeMillis();File out=new File(workspace,n);out.mkdirs();FileUtils.unzip(zip,out);projectRoot=out;loadProjectContext(out);showFiles(out);toast(projectContext.length()>0?"Proyecto importado · README cargado":"Proyecto importado · sin README");}catch(Exception e){error(e);}}
 private void loadProjectContext(File root){String key=root.getAbsolutePath();projectContext=getSharedPreferences("contexts",0).getString(key,"");if(projectContext.length()>0){if(aiHistory!=null)aiHistory.append("\nContexto resumido cargado ✓\n");return;}File readme=findReadme(root,0);if(readme!=null)try{String text=FileUtils.read(readme);projectContext=text.substring(0,Math.min(text.length(),12000));if(!contextAttempts.contains(key)){contextAttempts.add(key);if(aiHistory!=null)aiHistory.append("\nREADME encontrado · preparando contexto una vez…\n");summarizeProjectContext(root,readme,text);}}catch(Exception ignored){}}
 private void summarizeProjectContext(final File root,final File readme,String text){android.content.SharedPreferences sp=getSharedPreferences(SettingsActivity.PREF,0);String url=sp.getString(SettingsActivity.URL,"");if(url.length()==0)return;String header=sp.getString(SettingsActivity.HEADER,"X-RetroAI-Key"),secret=sp.getString(SettingsActivity.SECRET,""),model=sp.getString(SettingsActivity.MODEL,"openrouter/free");String limited=text.substring(0,Math.min(text.length(),20000));AIClient.ask(url,header,secret,model,"Resume este README en máximo 1800 caracteres. Conserva propósito, tecnologías, estructura, compilación y decisiones importantes.","markdown",readme.getName(),limited,"",new AIClient.Callback(){public void done(final String ans,final Exception e){runOnUiThread(new Runnable(){public void run(){if(e==null&&ans!=null&&ans.length()>0){projectContext=ans;getSharedPreferences("contexts",0).edit().putString(root.getAbsolutePath(),ans).apply();if(aiHistory!=null)aiHistory.append("Contexto del proyecto resumido y guardado ✓\n");toast("Contexto README listo");}}});}});}
 private File findReadme(File dir,int depth){if(dir==null||depth>3)return null;String[] preferred={"README.md","README.txt","README"};for(String n:preferred){File f=new File(dir,n);if(f.isFile())return f;}File[] kids=dir.listFiles();if(kids!=null)for(File f:kids)if(f.isDirectory()){File found=findReadme(f,depth+1);if(found!=null)return found;}return null;}
 private void openFile(File f){if(!f.isFile()){toast("No existe el archivo");return;}for(DocumentTab d:docs)if(d.file.equals(f)){bind(d);return;}try{if(f.length()>2*1024*1024){toast("Archivo demasiado grande para esta versión");return;}DocumentTab d=new DocumentTab(f,FileUtils.read(f));docs.add(d);bind(d);}catch(Exception e){error(e);}}
 private void newFile(){final EditText name=new EditText(this);name.setHint("NuevoArchivo.java");new AlertDialog.Builder(this).setTitle("Nuevo archivo").setView(name).setPositiveButton("CREAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){try{File dir=currentDir!=null&&currentDir.isDirectory()?currentDir:workspace;File f=new File(dir,name.getText().toString().trim());FileUtils.write(f,"");openFile(f);showFiles(dir);}catch(Exception e){error(e);}}}).setNegativeButton("CANCELAR",null).show();}
 private void bind(DocumentTab d){if(active!=null)active.cursor=editor.getSelectionStart();active=d;undo.clear();redo.clear();binding=true;editor.setText(d.text);editor.setSelection(Math.min(d.cursor,editor.length()));binding=false;SyntaxHighlighter.apply(editor.getText(),d.file);refreshTabs();updateStatus();}
 private void undo(){if(undo.isEmpty())return;redo.addLast(editor.getText().toString());setHistoryText(undo.removeLast());}
 private void redo(){if(redo.isEmpty())return;undo.addLast(editor.getText().toString());setHistoryText(redo.removeLast());}
 private void setHistoryText(String s){binding=true;editor.setText(s);binding=false;if(active!=null){active.text=s;active.dirty=true;}editor.setSelection(editor.length());scheduleHighlight();refreshTabs();}
 private void refreshTabs(){tabs.removeAllViews();for(final DocumentTab d:docs){TextView t=button(d.name()+"  ×");t.setBackgroundColor(d==active?Color.rgb(125,82,57):Color.rgb(155,120,95));t.setOnClickListener(new View.OnClickListener(){public void onClick(View v){bind(d);}});t.setOnLongClickListener(new View.OnLongClickListener(){public boolean onLongClick(View v){close(d);return true;}});tabs.addView(t,new LinearLayout.LayoutParams(-2,44));}}
 private void close(final DocumentTab d){if(d.dirty){new AlertDialog.Builder(this).setMessage("Guardar cambios en "+d.file.getName()+"?").setPositiveButton("GUARDAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface x,int w){save(d);remove(d);}}).setNegativeButton("DESCARTAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface x,int w){remove(d);}}).setNeutralButton("CANCELAR",null).show();}else remove(d);}
 private void remove(DocumentTab d){int i=docs.indexOf(d);docs.remove(d);active=null;if(!docs.isEmpty())bind(docs.get(Math.max(0,i-1)));else{binding=true;editor.setText("");binding=false;refreshTabs();updateStatus();}}
 private void save(DocumentTab d){if(d==null)return;try{if(d==active)d.text=editor.getText().toString();FileUtils.write(d.file,d.text);d.dirty=false;refreshTabs();toast("Guardado: "+d.file.getName());}catch(Exception e){error(e);}}
 private void exportZip(){final EditText path=new EditText(this);File base=currentDir==null?workspace:currentDir;while(base.getParentFile()!=null&&!base.getParentFile().equals(workspace)&&base.getAbsolutePath().startsWith(workspace.getAbsolutePath()))base=base.getParentFile();final File project=base;path.setText("/sdcard/"+project.getName()+"_editado.zip");new AlertDialog.Builder(this).setTitle("Exportar ZIP a").setView(path).setPositiveButton("EXPORTAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){try{for(DocumentTab x:docs)save(x);FileUtils.zip(project,new File(path.getText().toString()));toast("ZIP exportado");}catch(Exception e){error(e);}}}).setNegativeButton("CANCELAR",null).show();}
 private void findText(){final EditText q=new EditText(this);new AlertDialog.Builder(this).setTitle("Buscar texto").setView(q).setPositiveButton("BUSCAR",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){int from=Math.max(0,editor.getSelectionEnd());int at=editor.getText().toString().indexOf(q.getText().toString(),from);if(at<0)at=editor.getText().toString().indexOf(q.getText().toString());if(at>=0)editor.setSelection(at,at+q.length());else toast("No encontrado");}}).show();}
 private void askAI(){if(active==null){toast("Abre un archivo primero");return;}final String question=aiInput.getText().toString().trim();if(question.length()==0)return;android.content.SharedPreferences sp=getSharedPreferences(SettingsActivity.PREF,0);String url=sp.getString(SettingsActivity.URL,"");String header=sp.getString(SettingsActivity.HEADER,"X-RetroAI-Key"),secret=sp.getString(SettingsActivity.SECRET,""),model=sp.getString(SettingsActivity.MODEL,"openrouter/free");if(url.length()==0){toast("Configura la URL de Render");return;}int a=editor.getSelectionStart(),b=editor.getSelectionEnd();final String code=a!=b?editor.getText().subSequence(Math.min(a,b),Math.max(a,b)).toString():editor.getText().toString();final String fileName=active.file.getName(),lang=extension(active.file);aiInput.setText("");aiHistory.append("\nTú: "+question+"\nOliver IA: consultando…\n");scrollAi();AIClient.ask(url,header,secret,model,question,lang,fileName,code,projectContext,new AIClient.Callback(){public void done(final String ans,final Exception e){runOnUiThread(new Runnable(){public void run(){String old=aiHistory.getText().toString();int p=old.lastIndexOf("Oliver IA: consultando…");if(p>=0)old=old.substring(0,p);aiHistory.setText(old+"Oliver IA: "+(e==null?ans:friendlyAiError(e))+"\n");scrollAi();}});}});}
 private String friendlyAiError(Exception e){String s=String.valueOf(e.getMessage());if(s.indexOf("401")>=0)return "Clave incorrecta. Revisa APP_SHARED_KEY.";if(s.indexOf("SSL")>=0||s.indexOf("handshake")>=0)return "No se pudo establecer HTTPS. Verifica conexión y Google Play Services.";return "Error: "+s;}
 private void scrollAi(){aiScroll.post(new Runnable(){public void run(){aiScroll.fullScroll(View.FOCUS_DOWN);}});}
 private void scheduleHighlight(){if(highlightTask!=null)handler.removeCallbacks(highlightTask);highlightTask=new Runnable(){public void run(){if(active!=null){int p=editor.getSelectionStart();binding=true;SyntaxHighlighter.apply(editor.getText(),active.file);binding=false;try{editor.setSelection(Math.min(p,editor.length()));}catch(Exception ignored){}}}};handler.postDelayed(highlightTask,450);}
 private void updateStatus(){if(active==null){status.setText("Sin archivo");return;}int p=editor.getSelectionStart(),line=1,col=1;String s=editor.getText().toString();for(int i=0;i<p&&i<s.length();i++){if(s.charAt(i)=='\n'){line++;col=1;}else col++;}status.setText("Ln "+line+" : Col "+col+"    "+extension(active.file).toUpperCase());}
 private String extension(File f){String n=f.getName();int p=n.lastIndexOf('.');return p>=0?n.substring(p+1):"txt";}private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}private void error(Exception e){new AlertDialog.Builder(this).setTitle("Error").setMessage(e.getMessage()).setPositiveButton("ACEPTAR",null).show();}
 @Override public void onBackPressed(){if(active!=null&&active.dirty){close(active);}else super.onBackPressed();}
}
