plugins { id 'com.android.application' }

android {
    namespace 'cl.will.codepadai'
    compileSdk 33
    defaultConfig {
        applicationId 'cl.will.codepadai'
        minSdk 17
        targetSdk 28
        versionCode 6
        versionName '0.4.0-beta'
    }
}

dependencies {
    implementation 'org.conscrypt:conscrypt-android:2.5.2'
}
